baseURL = "https://rightinchrist.github.io/dr-brooke-goldner/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Dr. Brooke Goldner"
# copyright = "Copy, _right?_ :thinking_face:"
theme = "lynx"
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Dr. Brooke Goldner"
  headline = "Dr. Brooke Goldner's Official Links"
  # image = "img/author.jpg"  # path relative to static directory

  links = [
    # { email = "mailto:hello@your_domain.com" },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    # { bluesky = "https://bsky.app/profile/username" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
    { website = { href = "https://goodbyelupus.com/", text = "Official Website" } },
    { instagram = { href = "https://www.instagram.com/goodbyelupus/", text = "Instagram" } },
    { youtube = { href = "https://www.youtube.com/@BrookeGoldnerMD", text = "YouTube" } },
    { x = { href = "https://x.com/VeganMedicalDoc", text = "X formerly Twitter" }},
    { website = {href = "https://www.forksoverknives.com/contributors/brooke-goldner-md/", text = "Forks Over Knives" }},
    { website = {href = "https://podcasts.apple.com/us/podcast/brooke-goldner-md-healing-lupus-and-autoimmune/id1031359815?i=1000473799622", text = "Chris Beat Cancer"}},
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
  [[module.imports]]
    path = "github.com/jpanther/lynx"
